# Generated by Django 5.2.4 on 2025-07-09 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='categoria_padrao',
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='metrica',
            field=models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilo'), ('L', 'Litro')], max_length=2),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
