# Generated by Django 5.2.4 on 2025-07-09 22:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_estoque_categoria_padrao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='validade',
            new_name='dataValidade',
        ),
        migrations.AddField(
            model_name='produto',
            name='dataCadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='dataModificacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
