# Generated by Django 5.2.4 on 2025-07-10 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_validade_produto_datavalidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('intervalo_valor', models.PositiveIntegerField(default=30)),
                ('intervalo_tipo', models.CharField(choices=[('dias', 'Dias'), ('meses', 'Meses'), ('anos', 'Anos')], default='meses', max_length=6)),
                ('cota_minima', models.PositiveIntegerField()),
                ('ultima_compra', models.DateField(blank=True, null=True)),
                ('ignorar_ate_logout', models.BooleanField(default=False)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_recorrentes', to='App.produto')),
            ],
        ),
    ]
