# Generated by Django 5.2.4 on 2025-07-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_finalizar_fk_metricas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprarecorrente',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='comprarecorrente',
            name='intervalo_tipo',
        ),
        migrations.RemoveField(
            model_name='comprarecorrente',
            name='intervalo_valor',
        ),
        migrations.RemoveField(
            model_name='comprarecorrente',
            name='ultima_compra',
        ),
        migrations.AddField(
            model_name='comprarecorrente',
            name='checar_periodicamente',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comprarecorrente',
            name='cota_minima',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
